module.exports = [
    [
        {
            dueDate: '2021-01-11',
            priority: '1',
            title: 'TO DO Task 1',
            description: 'Description of TO DO task 1',
            reminderDate: '2020-12-12',
            status: 'To Do',
            tags: ['tag1'],
            subtasks: [
                'Do something before',
                'Do another thing before this task',
            ],
            dependencies: [],
        },
        {
            dueDate: '2020-12-29',
            priority: '1',
            title: 'TO DO Task 2',
            description: 'Description of TO DO task 2',
            reminderDate: '2020-12-19',
            status: 'To Do',
            tags: ['tag1', 'tag2'],
            subtasks: [
                'Do something before',
                'Do another thing before this task',
            ],
            dependencies: [],
        },
        {
            dueDate: '2020-12-17',
            priority: '1',
            title: 'TO DO Task 3',
            description: 'Description of TO DO task 3',
            reminderDate: '2020-12-11',
            status: 'To Do',
            tags: ['tag1', 'tag2', 'tag3'],
            subtasks: ['Go to the bank'],
            dependencies: [],
        },
        {
            dueDate: '2020-12-20',
            priority: '1',
            title: 'IN PROGRESS Task 1',
            description: 'Description of IN PROGRESS task 1',
            reminderDate: '2020-12-19',
            status: 'In Progress',
            tags: ['tag1', 'tag2'],
            subtasks: ['Go to taco bell'],
            dependencies: [],
        },
        {
            dueDate: '2020-12-17',
            priority: '1',
            title: 'IN PROGRESS Task 2',
            description: 'Description of IN PROGRESS task 2',
            reminderDate: '2020-12-16',
            status: 'In Progress',
            tags: ['tag2'],
            subtasks: ['Eat a burrito'],
            dependencies: [],
        },
        {
            dueDate: '2020-12-19',
            priority: '1',
            title: 'DONE Task 1',
            description: 'Description of DONE task 1',
            reminderDate: '2020-12-18',
            status: 'Done',
            tags: ['tag1'],
            subtasks: [],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 1',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: [
                'Do something before',
                'Do another thing before this task',
            ],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 2',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: [],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 3',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: [],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 4',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: [
                'Do something before',
                'Do another thing before this task',
            ],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 5',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: [],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 6',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: ['Do that thing', 'Do this thing'],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 7',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: ['Do that thing', 'Do this thing'],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 8',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: [],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 9',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: ['Do that thing', 'Do this thing'],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 10',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: [],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 11',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: ['Do that thing', 'Do this thing'],
            dependencies: [],
        },
        {
            dueDate: '2020-12-12',
            priority: '1',
            title: 'ARCHIVED Task 12',
            description: 'Description of ARCHIVED task 1',
            reminderDate: '2020-12-02',
            status: 'Archived',
            tags: ['tag1'],
            subtasks: ['Do that thing', 'Do this thing'],
            dependencies: [],
        },
    ],
];
